//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextStepMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSDbEntities : DbContext
    {
        public CMSDbEntities()
            : base("name=CMSDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLogin> AdminLogins { get; set; }
        public virtual DbSet<CombomPanel> CombomPanels { get; set; }
        public virtual DbSet<GalleryImage> GalleryImages { get; set; }
        public virtual DbSet<GalleryPanel> GalleryPanels { get; set; }
        public virtual DbSet<ImageFullSize> ImageFullSizes { get; set; }
        public virtual DbSet<PageSetting> PageSettings { get; set; }
        public virtual DbSet<Panel> Panels { get; set; }
        public virtual DbSet<PanelStyle> PanelStyles { get; set; }
        public virtual DbSet<PicturePanel> PicturePanels { get; set; }
        public virtual DbSet<SiteStyleSheet> SiteStyleSheets { get; set; }
        public virtual DbSet<TextPanel> TextPanels { get; set; }
        public virtual DbSet<VideoTable> VideoTables { get; set; }
        public virtual DbSet<PageSettingDomain> PageSettingDomains { get; set; }
    }
}
