//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextStepMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelStyle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PanelStyle()
        {
            this.Panels = new HashSet<Panel>();
        }
    
        public int Id { get; set; }
        public string StyleName { get; set; }
        public string color_panel_context { get; set; }
        public string color_panel_title { get; set; }
        public string color_panel_background { get; set; }
        public string font_family_panel_context { get; set; }
        public string font_family_panel_title { get; set; }
        public int PageSettingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Panel> Panels { get; set; }
        public virtual PageSetting PageSetting { get; set; }
    }
}
