//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextStepMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel
    {
        public int Panel_Id { get; set; }
        public string MenuTag { get; set; }
        public int StyleSheet { get; set; }
        public string UnderMenuTag { get; set; }
        public int PageSettingId { get; set; }
        public Nullable<int> MenuIndex { get; set; }
        public Nullable<int> UnderMenuIndex { get; set; }
    
        public virtual CombomPanel CombomPanel { get; set; }
        public virtual GalleryPanel GalleryPanel { get; set; }
        public virtual PanelStyle PanelStyle { get; set; }
        public virtual PicturePanel PicturePanel { get; set; }
        public virtual TextPanel TextPanel { get; set; }
        public virtual VideoTable VideoTable { get; set; }
        public virtual PageSetting PageSetting { get; set; }
    }
}
