//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextStepMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteStyleSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiteStyleSheet()
        {
            this.PageSettings = new HashSet<PageSetting>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string color_header_text { get; set; }
        public string color_header_title { get; set; }
        public string color_header_background { get; set; }
        public string color_site_background { get; set; }
        public string font_family_header { get; set; }
        public string font_family_header_menu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageSetting> PageSettings { get; set; }
    }
}
